### ISSUE TITLE
Cofoja not working in java 1.8

### ISSUE THREAD

**Issue by nhatminhle** [nhatminhle/cofoja#39]
_From [robertje...@gmail.com](https://code.google.com/u/117483208577497946372/) on July 27, 2013 09:18:43_

What steps will reproduce the problem? 1. Normal usage of Cofoja What is the expected output? What do you see instead? Normal behavior instead I'm getting : 

build:
    [mkdir] Created dir: C:\Users\jesse\git\cofoja\target.apt_generated
    [javac] C:\Users\jesse\git\cofoja\cofoja-build.xml:39: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to C:\Users\jesse\git\cofoja\target.apt_generated
    [javac] An annotation processor threw an uncaught exception.
    [javac] Consult the following stack trace for details.
    [javac] java.lang.NoClassDefFoundError: com/sun/tools/javac/main/OptionName
    [javac]     at com.google.java.contract.core.apt.AnnotationProcessor.setupPaths(AnnotationProcessor.java:225)
    [javac]     at com.google.java.contract.core.apt.AnnotationProcessor.init(AnnotationProcessor.java:148)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:503)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:600)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:693)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:94)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1020)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1154)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1146)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:832)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:517)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:376)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:365)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:356)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:77)
    [javac]     at com.sun.tools.javac.Main.main(Main.java:62)
    [javac] Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.main.OptionName What version of the product are you using? On what operating system? I'm using cofoja-1.1-20130405.jar on windows 7 Please provide any additional information below. See https://groups.google.com/forum/#!topic/cofoja/3q8Ol5nVnOY for a workaround.

_Original issue: http://code.google.com/p/cofoja/issues/detail?id=39_
